name: ci

on:
  push:
    branches:
      - main

jobs:
  docker-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        pg_version: [14, 13]
        base_image: [alpine, debian]
    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3
      - name: qemu_setup
        uses: docker/setup-qemu-action@8b122486cedac8393e77aa9734c3528886e4a1a8 # tag=v2
      - name: buildx_setup
        uses: docker/setup-buildx-action@dc7b9719a96d48369863986a06765841d7ea23f6 # tag=v2
      - name: get_tag
        run: |
          TAG=$(curl -s https://api.github.com/repos/bytesandbrains/h3-pg/releases/latest | jq -r '.tag_name')
          echo "TAG=$TAG" >> $GITHUB_ENV
      - name: docker_login
        uses: docker/login-action@49ed152c8eca782a232dede0303416e8f356c37b # tag=v2 
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: build docker image
        id: docker_build
        uses: docker/build-push-action@e551b19e49efd4e98792db7592c17c09b89db8d8 # tag=v3
        with:
          push: true
          platforms: linux/amd64
          tags: ghcr.io/boredland/h3-pg:${{ matrix.pg_version }}-${{ matrix.base_image }}-${{ env.TAG }},ghcr.io/boredland/h3-pg:${{ matrix.pg_version }}-${{ matrix.base_image }}
          file: ${{ matrix.pg_version }}-${{ matrix.base_image }}.Dockerfile
          build-args: |
            H3_PG_VERSION=${{ env.TAG }}
          cache-from: type=registry,ref=ghcr.io/boredland/h3-pg:cache-${{ matrix.pg_version }}-${{ matrix.base_image }}
          cache-to: type=registry,ref=ghcr.io/boredland/h3-pg:cache-${{ matrix.pg_version }}-${{ matrix.base_image }}
